spring:
  profiles:
    active: prod


  redis:
    host: 192.168.48.128
    port: 6379
    password: TEST

  session:
    store-type: redis
    redis:
      flush-mode: on_save

server:
  port: 25000

  servlet:
    session:
      timeout: 600